.deploy_docs: &deploy_docs
  image: nxpleuvenjenkins/doxygen

  before_script:
    - apt-get update -y
    - apt-get install -y sshpass openssh-client

deploy:docs:dev:
  <<: *deploy_docs

  script:
    - doxygen Doxyfile

  only:
    refs:
      - develop

.deploy_docker: &deploy_docker
  image: docker:18.09.7

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind

  before_script:
    - docker build . --tag toliak/course-project-2019:$TAG_NAME
    - docker login --username toliak -p $DOCKERHUB_KEY

  script:
    - docker push toliak/course-project-2019:$TAG_NAME

  only:
    changes:
      - Dockerfile
      - Pipfile
      - .gitlab-ci.yml

deploy:docker:prod:
  <<: *deploy_docker

  variables:
    $TAG_NAME: "master"

  only:
    refs:
      - master

deploy:docker:dev:
  <<: *deploy_docker

  variables:
    $TAG_NAME: "dev"

  only:
    refs:
      - develop