stages:
  - build
  - test
#  - deploy


.env_docker: &env_docker
  image: docker:18.09.7

  stage: build

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind

build docker:
  <<: *env_docker

  script:
    - docker build . --tag deploy_image
    - mkdir -p /var/deploy/images
    - docker save -o /var/deploy/images/deploy_image.tar deploy_image

  only:
    changes:
      - Dockerfile
      - Pipfile
      - .gitlab-ci.yml
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /var/deploy/images/
    policy: pull


build docs:
  image: nxpleuvenjenkins/doxygen

  stage: build

  script:
    - doxygen Doxyfile
    - mkdir -p /var/deploy/doxygen
    - cp -rv doxygen-build/ /var/deploy/doxygen/

  only:
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /var/deploy/doxygen/
    policy: pull

tests:
  <<: *env_docker

  script:
    - docker load --input /var/deploy/images/deploy_image.tar
    - docker run -t --rm -v $(pwd):/opt/builder/ -w /opt/builder/tests deploy_image pytest .

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /var/deploy/images/
    policy: push
