stages:
  - build
  - test
  - deploy


.env_docker: &env_docker
  image: docker:18.09.7

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind


build docker:
  <<: *env_docker

  stage: build

  script:
    - docker build . --tag deploy_image
    - mkdir -p images/
    - docker save -o images/deploy_image.tar deploy_image

  only:
    changes:
      - Dockerfile
      - Pipfile

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: push

build docs:
  image: python:3.7.4-buster

  stage: build

  before_script:
    - HOME_DIR=$(pwd)
    - apt-get update -y
    - apt-get install -y flex bison texlive-font-utils cmake git
    - cd /tmp
    - git clone https://github.com/doxygen/doxygen.git
    - cd doxygen
    - git checkout Release_1_8_16
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" ..
    - make -j 4
    - make install

  script:
    - cd $HOME_DIR
    - pip3 install doxypypy
    - ./scripts/doxygen.sh

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docs
    paths:
      - doxygen-build/
    policy: push


test and coverage:
  <<: *env_docker

  stage: test

  before_script:
    - docker load --input images/deploy_image.tar

  script:
    - docker run -t --rm -v $(pwd):/opt/builder/ -w /opt/builder/tests deploy_image ../scripts/tests.sh

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: pull


deploy docs:
  image: debian:buster

  stage: deploy

  before_script:
    - apt-get update -y
    - apt-get install -y sshpass openssh-client
    - if [ ${CI_COMMIT_REF_SLUG} = master ]; then SUB_DIR=latest; else SUB_DIR=dev; fi
    - echo $SUB_DIR

  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo -e "Host ToliakRuVM\n\tHostname 127.0.0.1\n\tUser root" >> ~/.ssh/config
    - echo -e "\tIdentityFile ~/.ssh/ToliakRuVM\n\tIdentitiesOnly no\n\n" >> ~/.ssh/config
    - sshpass -p $CI_PASSWORD_VISITOR scp visitor@skeak.toliak.ru:~/.ssh/ToliakRuVM ~/.ssh/ToliakRuVM
    - sshpass -p $CI_PASSWORD_VISITOR ssh -L 127.0.0.1:8022:ToliakRuVM:22 visitor@skeak.toliak.ru -f 'sleep 1000'
    - cd doxygen-build/html/
    - scp -r -P 8022 . ToliakRuVM:/usr/share/nginx/toliak.ru/course-project/docs/$SUB_DIR/

  only:
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docs
    paths:
      - doxygen-build/
    policy: pull

deploy docker:
  <<: *env_docker

  stage: deploy

  before_script:
    - if [ ${CI_COMMIT_REF_SLUG} = master ]; then TAG_NAME=latest; else TAG_NAME=dev; fi
    - echo $TAG_NAME

  script:
    - docker load --input images/deploy_image.tar
    - docker tag deploy_image toliak/course-project-2019:$TAG_NAME
    - docker login --username toliak -p $DOCKERHUB_KEY
    - docker push toliak/course-project-2019:$TAG_NAME

  only:
    changes:
      - Dockerfile
      - Pipfile
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: pull