stages:
  - build
  - test
  - deploy

.deploy_docker: &deploy_docker
  only:
    changes:
      - Dockerfile
      - Pipfile
      - .gitlab-ci.yml

.env_docker: &env_docker
  image: docker:18.09.7

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind

build docker:
  <<: *env_docker
  <<: *deploy_docker

  stage: build

  script:
    - docker build . --tag deploy_image
    - mkdir -p images/
    - docker save -o images/deploy_image.tar deploy_image

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: push


build docs:
  image: nxpleuvenjenkins/doxygen

  stage: build

  script:
    - doxygen Doxyfile

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docs
    paths:
      - doxygen-build/
    policy: push


test and coverage:
  <<: *env_docker

  stage: test

  before_script:
    - docker load --input images/deploy_image.tar

  script:
    - docker run -t --rm -v $(pwd):/opt/builder/ -w /opt/builder/tests deploy_image ../scripts/tests.sh

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: pull


deploy docs:
  image: debian:buster

  stage: deploy

  before_script:
    - apt-get update -y
    - apt-get install -y sshpass openssh-client
    - \[\[ ${CI_COMMIT_REF_SLUG} = master \]\] \&\& SUB_DIR=latest || SUB_DIR=dev
    - echo $SUB_DIR

  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo -e "Host ToliakRuVM\n\tHostname 127.0.0.1\n\tUser root" >> ~/.ssh/config
    - echo -e "\tIdentityFile ~/.ssh/ToliakRuVM\n\tIdentitiesOnly no\n\n" >> ~/.ssh/config
    - sshpass -p $CI_PASSWORD_VISITOR scp visitor@skeak.toliak.ru:~/.ssh/ToliakRuVM ~/.ssh/ToliakRuVM
    - sshpass -p $CI_PASSWORD_VISITOR ssh -L 127.0.0.1:8022:ToliakRuVM:22 visitor@skeak.toliak.ru -f 'sleep 1000'
    - cd doxygen-build/
    - scp -r -P 8022 . ToliakRuVM:/usr/share/nginx/toliak.ru/course-project/docs/$SUB_DIR/

  only:
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docs
    paths:
      - doxygen-build/
    policy: pull

deploy docker:
  <<: *env_docker
  <<: *deploy_docker

  stage: deploy

  before_script:
    - [[ ${CI_COMMIT_REF_SLUG} = master ]] \&\& TAG_NAME=latest || TAG_NAME=dev
    - echo $TAG_NAME

  script:
    - docker load --input images/deploy_image.tar
    - docker tag deploy_image toliak/course-project-2019:$TAG_NAME
    - docker login --username toliak -p $DOCKERHUB_KEY
    - docker push toliak/course-project-2019:$TAG_NAME

  only:
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: pull