stages:
  - build
  - test
#  - deploy


.env_docker: &env_docker
  image: docker:18.09.7

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind

build docker:
  <<: *env_docker

  stage: build

  script:
    - docker build . --tag deploy_image
    - mkdir -p images/
    - docker save -o images/deploy_image.tar deploy_image

  only:
    changes:
      - Dockerfile
      - Pipfile
      - .gitlab-ci.yml
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: push


build docs:
  image: nxpleuvenjenkins/doxygen

  stage: build

  script:
    - doxygen Doxyfile

  only:
    refs:
      - develop
      - master

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docs
    paths:
      - doxygen-build/
    policy: push

tests:
  <<: *env_docker

  stage: test

  script:
    - docker load --input images/deploy_image.tar
    - docker run -t --rm -v $(pwd):/opt/builder/ -w /opt/builder/tests deploy_image pytest .

  cache:
    key: ${CI_COMMIT_REF_SLUG}_docker
    paths:
      - images/
    policy: pull
