.deploy_docker: &deployment_script
  image: docker:18.09.7

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind

  before_script:
    - docker info
    - docker build . --tag toliak/course-project-2019
    - docker login --username toliak -p $DOCKERHUB_KEY

deploy:docker:prod:
  <<: *deployment_script

  script:
    - docker push toliak/course-project-2019:latest

  only:
    changes:
      - Dockerfile
      - Pipfile
    refs:
      - master

deploy:docker:dev:
  <<: *deployment_script

  script:
    - docker push toliak/course-project-2019:dev

  only:
    changes:
      - Dockerfile
      - Pipfile
    refs:
      - develop