deploy docker:
  image: docker:latest

  script:
    - docker build . --tag toliak/course-project-2019
    - docker login --username Toliak -p $DOCKER_KEY
    - docker push toliak/course-project-2019:latest

  only:
    changes:
      - Dockerfile
      - Pipfile
